### ISSUE TITLE
Projects are not loaded until the app is restarted

### ISSUE THREAD

**Issue by jhohlfeld** [herrhelms/beekeeper#1]
When I add or change projects, I have to re-launch the Beekeeper app.

It would be nice to have this done automatically.

**Comment by herrhelms** [comment]
Agreed - and boom - this is fixed! You need to [re-download the app](http://github.com/herrhelms/beekeeper/blob/master/dist/BeeKeeper.zip) or `git pull` & build it again yourself. **happy timetracking!**
